# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Install Meteor
      - run: curl https://install.meteor.com | sh

      # https://github.com/meteor/meteor/issues/4019
      - run: apt-get install language-pack-en -y

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tests/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install dependencies
      - run: cd tests && meteor npm install

      - save_cache:
          paths:
            - tests/node_modules
          key: v1-dependencies-{{ checksum "tests/package.json" }}

      # run tests!
      - run: cd tests && npm test
